name: CI

on:
  push:
    branches:
      - release/*
    types: [created]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yanamura/git-flow-merge-action@v1
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${GITHUB_REF#refs/heads/}
    
    
